safe: true
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor

gems:
  - jekyll-sitemap

permalink: /:title/
timezone: Europe/Stockholm

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

url: 'https://svendahlstrand.se'
