permalink: /:title/
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - vendor
markdown: redcarpet
timezone: Europe/Stockholm
gems:
  - jekyll-sitemap
collections:
  wiki:
    output: true
    permalink: /wiki/:path/
defaults:
  - scope:
      path: ""
      type: wiki
    values:
      layout: wiki
