exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
include:
  - _pages
  - _redirects
  - .well-known

collections:
  notes:
    output: true
    permalink: :name/

plugins:
  - jekyll-image-size
  - jekyll-sitemap

permalink: /:title/
timezone: Europe/Stockholm

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

defaults:
  -
    scope:
      path: ""
    values:
      language: "en"
  - scope:
      type: "notes"
    values:
      layout: "note"

languages: ["sv", "en"]

url: "https://dahlstrand.net"
