permalink: /:title/
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
timezone: Europe/Stockholm
gems:
  - jekyll-sitemap
