exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
include:
  - _pages

gems:
  - jekyll-sitemap

permalink: /:title/
timezone: Europe/Stockholm

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

defaults:
  -
    scope:
      path: ""
    values:
      language: "sv"
  -
    scope:
      path: "en"
    values:
      language: "en"
  -
    scope:
      path: "en"
      type: posts
    values:
      permalink: /en/:title/


languages: ["sv", "en"]
