exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
include:
  - _pages
  - _redirects

plugins:
  - jekyll-sitemap

permalink: /:title/
timezone: Europe/Stockholm

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

defaults:
  -
    scope:
      path: ""
    values:
      language: "en"

languages: ["sv", "en"]

url: "https://svendahlstrand.se"
