permalink: /:title/
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
markdown: redcarpet
redcarpet:
  extensions: ['autolink']
timezone: Europe/Stockholm
gems:
  - jekyll-sitemap
defaults:
  - scope:
      path: ""
      type: wiki
    values:
      layout: wiki
