name: Deploy Website over SFTP

on: [push]

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@master
      with:
        ruby-version: 2.6.x

    - name: Install gems
      run: bundle install --jobs 4 --retry 3

    - name: Build
      run: bundle exec jekyll build

    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.SFTP_HOST }}
        FTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        METHOD: sftp
        LOCAL_DIR: _site
        ARGS: --delete
