name: Jekyll

on: [push]

jobs:
  test:
    name: Build and run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@master
      with:
        ruby-version: 2.7.x
    - name: Install gems
      run: bundle install --jobs 4 --retry 3
    - name: Run tests
      run: bundle exec rake
